server:
  port: 10003
  error:
    include-message: always

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka

spring:
  application:
    name: Analytics
  kafka:
    topic:
      visitor: "visitor.analytics"
    streams:
      application-id: "analytics-service"
    store:
      visitor-store-name: "visitorStore"
    bootstrap-servers: "kafka1:9092,kafka2:9093,kafka3:9094"

management:
  endpoints:
    web:
      exposure:
        include: health, mappings, metrics