server:
  port: 10003
  error:
    include-message: always

spring:
  kafka:
    topic:
      visitor: "visitor.analytics"
    streams:
      application-id: "analytics-service"
    store:
      visitor-store-name: "visitorStore"
    bootstrap-servers: localhost:9092


