server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: admin

management:
  endpoints:
    web:
      exposure:
        include: health, mappings, metrics