server:
  port: 10001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: url-converter
  redirector:
    prefix: http://localhost:10002/redirector/
  kafka:
    topic:
      tiny-url: "tiny.url"
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

management:
  endpoints:
    web:
      exposure:
        include: health, mappings, metrics