server:
  port: 10001

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka

spring:
  application:
    name: url-converter
  redirector:
    prefix: http://url-redirector/redirector/
  kafka:
    topic:
      tiny-url: "tiny.url"
    bootstrap-servers: "kafka1:9092,kafka2:9093,kafka3:9094"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

management:
  endpoints:
    web:
      exposure:
        include: health, mappings, metrics