server:
  port: 10002
  error:
    include-message: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: url-redirector
  kafka:
    producer:
      value-serializer: org.apache.kafka.common.serialization.LongSerializer
    topic:
      tiny-url: "tiny.url"
      visitor: "visitor.analytics"
    streams:
      application-id: "tiny-url.redirector-service"
    store:
      tiny-url-store-name: "tinyUrlStore"
    bootstrap-servers: localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: health, mappings, metrics
